- merkle/accumulator.go
- merkle/accumulator_test.go
- merkle/multiproof_test.go
- types/encoding.go
- types/types.go
This PR expands test coverage in merkle to about 80%.  Still need to add coverage relating to RevertBlock but that should probably bring it around 90.
> merkle: expand test coverage

- consensus/validation.go
- consensus/validation_test.go
- merkle/multiproof.go
- types/encoding.go
- types/types.go
This implements the "dumb" version of attestations; basically just better-structured ArbitraryData. See #17 for discussion.
In this PR, all attestations are validated by consensus. It hadn't occurred to me until just now that perhaps attestations should be validated "lazily;" that is, the consumer of the attestation (e.g. a renter looking for host announcements) should be responsible for validating it. The rationale here is that verifying signatures is slow, so if you don't care about a particular attestation, why should you have to spend CPU cycles validating it?
A counterargument is that enforcing valid signatures in consensus is "safe by default;" no one can accidentally forget to check the signature. Equivalently, invalid signatures are prevented from ever making it on-chain in the …
> types,consensus: Implement Attestations

- internal/chainutil/chainutil_test.go
- internal/chainutil/store_test.go
Currently much of chainutil's coverage comes indirectly from other modules like `chain`.  This PR adds more direct coverage to chainutil.  It raises the coverage from 50% to a little over 75%.  The bulk of the remaining coverage is IO error checking code in store.go which would be pretty difficult to test (at least elegantly).
> Improve chainutil test coverage

- chain/manager_test.go
- internal/chainutil/store_test.go
Changes tests to use `TempDir()` instead of `os.MkdirTemp()`
> tests: use tb.TempDir()

- merkle/multiproof_corpusgen.go
- merkle/multiproof_fuzz.go
This adds a fuzzer targeting the `CompressedBlock.DecodeFrom` method.
Within a couple of minutes (beginning with the generated corpus) it was able to identify the bounds problem in MultiproofSize:
```
panic: runtime error: index out of range [768] with length 64
goroutine 1 [running]:
go.sia.tech/core/merkle.leavesByTree.func1(...)
/home/christopher/prog/go/src/go.sia.tech/core/merkle/multiproof.go:18
go.sia.tech/core/merkle.leavesByTree(0xc00028e000, 0x300, 0x300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/home/christopher/prog/go/src/go.sia.tech/core/merkle/multiproof.go:23 +0xe45
go.sia.tech/core/merkle.MultiproofSize(0xc00028e000, 0x300, 0x300, 0xc00028e000)
/home/christopher/prog/go/src/go.sia.tech/core/merkle/multiproof.go:60 +0xe9 …
```
> fuzz: fuzz CompressedBlock decoding

- merkle/multiproof.go
- types/encoding.go
Basically: instead of unconditionally writing the length-prefix for every field (and the `NewFoundationAddress`), we prefix the encoding with a bitfield, where a 1 bit means "this field is present." Most transactions only include inputs, outputs, and a miner fee, so on average this optimization saves about 100 bytes per txn. We only "pay the cost" of the bitfield when encoding a transaction that has *all* fields present, which pretty much never happens.
> types: Use bitfield to reduce encoded txn size

- consensus/update.go
- consensus/update_test.go
- types/types.go
This adds a new rule to consensus: If a contract is revised such that its revision number is `MaxRevisionNumber` (i.e. it cannot be revised further) and its valid outputs equal its missed outputs (i.e. the outcome will be the same whether a storage proof is provided or not), then the contract is resolved immediately.
Essentially, this reifies the "renew and clear" pattern established in v1, wherein a renter and host would "finalize" an old contract while simultaneously forming a new contract that inherits the old Merkle root. A big problem with this pattern was that the funds locked in the old contract would remain locked until the original `WindowEnd` height. With early resolution, we can fix this by releasing the locked funds immediately once it's clear that only one outcome is …
> Early contract resolution

- net/gateway/peer.go
- net/gateway/peer_test.go
`Header` is no longer an exported type, and no longer includes a `NetAddress` field. In fact, this address is no longer exchanged during the handshake at all. The reason we originally included it was so that the accepting peer could learn the dialing peer's listen address and add it to their list of potentially-connectable addresses. But we already call the `GetPeers` RPC on new pees immediately after connecting to them; so why not simply have the recipient include their own address in the response? (This is implemented in a soon-to-follow `siad` PR.) Furthermore, sometimes the dialing peer may not wish their listen address to be known; or they might not have a listen address at all, e.g. when downloading a checkpoint.
Still, there *are* reasons why we would want to know the network …
> net/gateway: Refactor Header

- chain/manager.go
- consensus/validation.go
- merkle/accumulator.go
- types/policy.go
- types/policy_test.go
- types/types.go
Domain separation prevents signatures from being reused in different contexts. This is important because objects in different domains can sometimes serialize to the same bytes. For example, a transaction might encode to the same bytes as an attestation; consequently, the same signature could be used to sign both objects. An attacker could exploit this in two ways: by tricking you into signing something innocuous, then reusing that signature to steal your coins; or by observing one of your publicly-broadcasted signatures, and then crafting a different object with the same encoding (e.g. an attestation) and broadcasting it with your signature attached.
The fix is simple: just add a unique prefix to every sighash. I went a bit further and added prefixes to other hashes as well, like block …
> all: Add domain-separation prefixes to most hashes

- consensus/update.go
- consensus/update_test.go
- merkle/accumulator.go
- merkle/accumulator_test.go
A block revert should ideally return the prior revision instead of returning the reverted revision
> consensus: use parent when reverting revisions

- consensus/update.go
- consensus/validation.go
Renames `BlockRewardTimelock` to `DefaultTimelock`, I thought this was better over having `BlockRewardTimelock`, `SiafundClaimTimelock`, and `ContractOutputTimelock`. Adds timelocks to contract resolution outputs.
> Add timelock to contract outputs

- host/executor.go
- host/host.go
- net/rhp/builder.go
- net/rhp/builder_test.go
- net/rhp/mdm.go
- net/rhp/rpc.go
- net/rhp/settings.go
Adds two new MDM instructions: `UpdateSector` and `SectorRoots`. `UpdateSector` takes an existing sector index in the program and overwrites the data. `SectorRoots` returns the program's current sector roots.
> mdm: add update and sector roots instructions

- consensus/update_test.go
- consensus/validation.go
- consensus/validation_test.go
- host/executor.go
- merkle/multiproof.go
- net/rhp/contracts.go
- types/encoding.go
- types/types.go
This brings `FileContract` into parity with other signed types, like `Attestation`. It will also make the upcoming contract renewal changes a bit cleaner.
Historically, the initial file contract hasn't been signed because it's redundant: each party is supplying inputs to the contract transaction, and they have to sign those inputs. But it bugs me that someone could broadcast a transaction that *claims* to form a contract with a particular host (by using their public key), even though the host actually knew nothing about it. Obviously, the host would then "fail" the storage proof, so these phony contracts could negatively impact a host's reputation. Requiring signatures on the initial contract prevents this.
> types: Move signatures into FileContract type

- consensus/update.go
- consensus/update_test.go
- consensus/validation.go
- merkle/multiproof.go
- net/rhp/contracts.go
- net/rhp/rpc.go
- net/rhp/session_test.go
- types/encoding.go
- types/types.go
Previously, a `FileContractRevision` could actually be a `FileContractResolution` if it satisfied certain properties. That felt a little too magic to me, so instead I moved the "early close" case into the `FileContractResolution` type. Now, a revision always revises, and a resolution always resolves.
...well, except that a resolution can also revise. But still, I think this is an improvement.
> types: Make 'early close' an explicit form of contract resolution

- consensus/update.go
In retrospect, this is obvious: a really low hash does not imply that more work was performed, only that the miner got lucky. We don't care *which* specific hash the miner found, only that it's below the required target.
This might cause some issues for tests, since you won't be able to make one chain heavier than another just by grinding a slightly better nonce; you'll have to mine additional blocks, or mess with the timestamps. Shouldn't be too bad.
> consensus: Fix how blocks contribute to TotalWork

- host/executor.go
- net/rhp/contracts.go
Removes signature validation from the validation functions, signatures would need to be validated externally. The primary motivation was changing `ValidateContractFinalization` to validate all fields except the signature fields to short-circuit the renew RPC before the host has the renter signatures, like `ValidateRenewal` and `ValidateContractFormation`. However, I'm unsure if the change makes sense for the other validation methods, like `ValidatePaymentRevision`, which would have the signatures immediately.
> Separate contract signature validation

- consensus/validation.go
Changes `ValidationContext.SigHash` to use `ContractSigHash` instead of encoding the `FileContract` to prevent contract signatures from invalidating the transaction signatures and adds the `Attestations` field.
> Cover Attestations in SigHash

- consensus/update_test.go
- consensus/validation.go
- consensus/validation_test.go
- internal/chainutil/chainutil.go
- merkle/multiproof.go
- net/rhp/rpc.go
- net/rhp/session_test.go
- types/encoding.go
- types/encoding_test.go
- types/types.go
I had originally thought that input signatures would need some additional metadata, like flags or an index, to indicate what part of the transaction they were signing. But I think we can get away without these: input signatures should just sign the entire transaction, always. There are a few fringe usecases for other types of signatures ([this](https://raghavsood.com/blog/2018/06/10/bitcoin-signature-types-sighash) is a good overview), but Sia doesn't benefit much from any of them. The only real "loss" is that you can't non-interactively sign an atomic swap transaction -- but you can still do it interactively by exchanging partially-signed transactions OOB (e.g. via Discord, which you'll probably be using to find swap partners anyway).
I also renamed `SigHash` to `InputSigHash`, for …
> Remove distinct InputSignature type

- net/rhp/rpc.go
- net/rhp/session_test.go
Changes the RHP types to send the host's contract signatures before the Siacoin input signatures as described in #52
> Send contract signatures earlier

- consensus/update.go
- consensus/update_test.go
- consensus/validation.go
- types/encoding.go
- types/types.go
This PR reifies contract renewals as a fourth type of contract resolution. The old contract is finalized (i.e. its revision number is maxed out) and marked resolved; the new contract is created; and importantly, a variable amount of SC may be "rolled over" from the old contract into the new contract.
After https://github.com/SiaFoundation/core/pull/43, I wasn't sure if rolling over funds like this could be done safely. But after talking to David about it, I feel pretty confident that this is okay. The key point is that *funds never leave a contract without a timelock*. You can roll funds from contract A->B (and B->C, and C->D), but when the final contract ends and the outputs are released, they'll be subject to the standard maturity delay. Likewise, the portion of the funds that *aren't* …
> First-class contract renewal

- host/host.go
- net/rhp/rpc.go
- net/rhp/session_test.go
Changes the contract formation requests to only accept a subset of the transaction fields instead of a transaction set, as mentioned in #55.
>  Restrict contract formation requests

- consensus/update.go
- consensus/update_test.go
- consensus/validation.go
Hosts cannot currently retrieve funds for empty contracts until after the proof window unless the renter finalizes the contract. This PR allows contract resolutions with empty storage proofs when the contract has a zero Merkle root.
> Allow empty storage proofs within the proof window

- merkle/multiproof_test.go
- types/encoding_test.go
- types/types.go
I was working on https://github.com/SiaFoundation/siad/pull/86 and I kept getting this "wrong number of separators" error.  Eventually I realized it was coming from here.  Also, looking at some of the other types, shouldn't all of the UnmarshalTexts operate on pointer receivers?
> Fix ElementID Unmarshaling

- consensus/validation.go
- consensus/validation_test.go
- merkle/multiproof.go
- types/encoding.go
- types/encoding_test.go
- types/policy.go
- types/policy_test.go
- types/types.go
The `SpendPolicy` type has historically been a real pain to work with. It's defined as an interface, which is a good fit for the underlying semantics (a set of possible policy types). But Go does not allow you to define methods on interfaces, which means `SpendPolicy` can't implement `EncoderTo`, `DecoderFrom`, `MarshalJSON`, or even `String()`. This is really annoying. It means we need a special `(Encoder).WritePolicy` method. It means we have to define a custom `MarshalJSON` method on every type that contains a `SpendPolicy`. etc.
You can *almost* get around this by adding those methods to the definition of `SpendPolicy`. But this falls apart when you want to *decode* a value, because there's no way to match a `nil` `SpendPolicy` to the concrete type that it *should* be decoded into. …
> Encapsulate SpendPolicy in concrete struct

- host/executor.go
- net/rhp/builder.go
- net/rhp/mdm.go
- net/rhp/rpc.go
The sheer number of methods here bothered me, so I consolidated them into a pair of top-level functions instead. I also moved the specifier methods into `writeInstruction`, for parity with `readInstruction`. (AFAIK, the `Specifier` method isn't needed anywhere else.) I think the latter is more justified than the former; there's certainly an argument to be made that methods like `RequiresFinalization` "belong" to their associated type. But the amount of code involved just didn't sit right with me.
> rhp: Consolidate Instruction methods

- .github/workflows/nightly.yml
- .github/workflows/test.yml
Adds Go 1.18 to the CI test versions. The `go.mod` is still 1.16, do we want to drop it?
> ci: add go 1.18

- types/policy.go
- types/policy_test.go
Replaces the rather complicated string indexing of the old ParseSpendPolicy with a more standard recursive parser.
> v2: use a more robust parser in ParseSpendPolicy

- chain/manager.go
- chain/manager_test.go
- consensus/scratch.go
- consensus/scratch_test.go
- consensus/state.go
- consensus/update.go
- consensus/update_test.go
- consensus/validation.go
- consensus/validation_test.go
- host/executor.go
- host/host.go
- internal/chainutil/chainutil.go
- internal/chainutil/chainutil_test.go
- internal/chainutil/store.go
- internal/chainutil/store_test.go
- net/gateway/rpc.go
- net/rhp/contracts.go
While preparing my talk on Utreexo, I realized that what we call a "validation context" is generally called the "chain state" in Bitcoin and elsewhere. Moreover, the state is actually a superset of the validation context. Consider that, in order to validate a block's timestamp, you only need to know the median timestamp of the last 11 blocks, i.e. a single `time.Time` value; but in order to *perform a state transition*, you need to store *all* 11 `time.Time` values.
I considered keeping `ValidationContext` around, with the idea that you could call `State.ValidationContext()` to get one (and then validate blocks using it), but ultimately it felt a bit pointless; unlike `State`, there really isn't any need to pass around `ValidationContext` values. You'd just be creating them in order to …
> ValidationContext -> State

- net/rhp/contracts.go
- net/rhp/contracts_test.go
Adds tests that try to trigger all of the error states in ValidateContractSignatures, ValidateContractFormation, ValidateContractRenewal, ValidateContractFinalization, ValidateProgramRevision, ValidatePaymentRevision.  Brings contracts.go coverage to over 90%.
> net/rhp: add contracts tests

- types/types.go
small oversight in `MissedHostPayout`
> MissedHostPayout

- go.mod
- go.sum
- rhp/v2/contracts.go
- rhp/v2/encoding.go
- rhp/v2/merkle.go
- rhp/v2/merkle_test.go
- rhp/v2/release.go
- rhp/v2/rhp.go
- rhp/v2/testing.go
- rhp/v2/transport.go
- rhp/v3/encoding.go
- rhp/v3/program.go
- rhp/v3/registry.go
- rhp/v3/rhp.go
- rhp/v3/transport.go
- types/types.go
- wallet/seed.go
This moves large swathes of shared RHP code from `renterd` and `hostd` into `core`.
Since this is `core`, the code is fairly low-level and avoids "making decisions." For example, `core` does not provide functions that actually *call* the RHP RPCs, nor any form of "handler" or "server" that decodes incoming RPCs and routes them to an appropriate function. That code still lives in `renterd` and `hostd`, respectively.
> rhp: Add packages

- rhp/v3/rhp.go
+ Adds missing RHPv3 instruction costs
+ Adds `ResourceCost` to be explicit about where the cost comes from.
+ Doesn't include memory or time costs from `siad`; need to discuss what values are appropriate or if we want them to be included.
+ Changes how bandwidth costs are calculated in the MDM to only include the inputs and outputs, not the protocol overhead.
> rhp/v3: add missing instruction costs

- rhp/v3/encoding.go
- rhp/v3/program.go
- rhp/v3/rhp.go
+ Adds a `ResourceCost.Total()` helper func
+ Removes the `SectorRoots` instruction, it doesn't exist in `siad`
+ Adds missing RPCExecute types
> rhpv3 additions

- rhp/v2/contracts.go
This PR fixes the math in `ContractRenewalCollateral` and `ContractFormationCollateral`.
1. both now use the same math to compute collateral given the `renterFunds` which we are about to put into a contract.
2. `costPerByte` now accounts for the storage duration. This should drive the cost up significantly and reduce the amount of collateral we put into contracts.
3. The collateral capping math in `ContractRenewalCollateral` now subtracts the delta from `newCollateral` which fixes the case of hitting the `MaxCollateral` with a `baseCollateral` that is smaller than `newCollateral`. Previously the `newCollateral` returned in that case was far too small.
4. Computing the collateral now multiplies the collateral by the duration of the contract as well. Otherwise we only add enough collateral …
> Fix newCollateral math in ContractRenewalCollateral

- rhp/v2/transport.go
The `Session` object in `renterd` uses the `Transport` to read and write without imposing any deadlines or timeouts, even though a context is being passed down into most functions. So essentially the `Transport` is not respecting the timeouts imposed on it. I want to expose `SetDeadline` to be able to set a deadline on the underlying connection.
edit: exposed `SetReadDeadline` and `SetWriteDeadline` while we're at it
> Expose conn.SetDeadline on Transport

- rhp/v2/transport.go
This PR adds a write deadline of one second right before trying to gracefully close a transport by sending `LoopExit`. This to prevent the graceful shutdown from blocking the close.
> Transport Close WriteDeadline

- chain/db_test.go
- v2/internal/chainutil/chainutil.go
- v2/types/currency.go
- wallet/address.go
Adds test that creates new chain.Manager and in memory DB, adds some blocks, ensures the block diffs are correct and checks that the SC and SF outputs from the transactions in the blocks are in the DB.
> Add Consensus/Chain Manager Test

- rhp/v2/transport.go
We need a `ForceClose` that doesn't try to gracefully close the transport by writing `LoopExit`. The reason for this is that the transport reuses bytes on write causing a data race is we try to close the transport from another thread.
> Add ForceClose to Transport

- rhp/v3/encoding.go
- rhp/v3/program.go
- rhp/v3/rhp.go
- rhp/v3/transport.go
This PR fixes some of the encoding issues in the new `rhp` code. I've only tested it with `ReadSector`. I decided to open a PR because I think Nate and I are working through the same issues so I figured we could consolidate our efforts into one PR/branch and get it merged. 
The main issues I think are:
> RHP Encoding Fixes

- rhp/v2/testnet.go
Temporarily adds testnet consts to `rhp/v2` for the tax hardfork. Enables testnet builds in hostd and renterd
> Add testnet tax override

- consensus/state.go
- consensus/update.go
- consensus/validation.go
- go.mod
- go.sum
I took a stab at addressing the issue that I alluded to in https://github.com/SiaFoundation/core/pull/95. The approach I ended up taking was a bit different than what I originally suggested. The problem with embedding the entire `NetworkParams` struct within `State` is that now you have to encode/decode all of those parameters every time you encode/decode a `State`. This is egregiously wasteful; the consensus DB would end up storing hundreds of thousands of copies of the same parameters. I suppose we could have the DB override the encoding of `State`, but you'd also have to override the encoding of any type that *contains* `State` (e.g. `Checkpoint`), and this would affect all future users of `State`, not just us.
It occurred to me that we could store just an ID, rather than the full …
> Network parameters

- chain/db.go
- chain/db_test.go
- chain/network.go
- consensus/state.go
- consensus/update.go
- consensus/validation.go
Take number 3 of #96 🙃 
In this approach, we add the network parameters as a field of `State`, but do not encode them. `Mainnet` and `Testnet` are defined in `chain`, keeping `consensus` pure.
I think I prefer this to #97; having a `Network` struct feels like the right abstraction, and this approach doesn't require hardcoding mainnet/testnet stuff into `consensus`.
> consensus: Add Network to State

- rhp/v3/encoding.go
- rhp/v3/rhp.go
Adding the types for the request and response of the RPCLatestRevision RPC to use in renterd.
> Add types for RPCLatestRevision

- rhp/v3/contracts.go
Adds the same helpers we already have for rhpv2 but slightly updated for rhpv3.
NOTE: `taxAdjustedPayout` is a copy-paste and exactly the same for rhpv2. Feel free to suggest a better place for it or to push a commit that moves it.
> Add helpers for rhpv3 contract renewals

- rhp/v3/rhp.go
Right now `RPCRenewSignatures` doesn't match `RPCRenewContractRenterSignatures` and `RPCRenewContractHostSignatures` from `siad`. So rhpv3 renewals fail due to a decoding error.
> Update RPCRenewSignatures to match siad type

- chain/network.go
- consensus/state.go
This PR adds a `Name` field to the `Network` object in the `consensus` package. By adding the network name the UI can differentiate between the `mainnet` and the `testnet` and adjust accordingly.
> Network Name

- rhp/v3/rhp.go
This PR adds the `InitProgramHelper` which makes it a bit nicer to compute costs for programs.
e.g. computing the cost of a read sector program becomes this
```go
rc := pt.InitProgramCost()
rc.Add(pt.ReadSectorCost(rhpv2.SectorSize))
cost, _ := rc.Total()
```
where previously we couldn't make use of the `ResourceCost` type for the base cost.
Also snuck in a receiver change that Nate proposed.
> Add InitProgramCost helper 

- types/types.go
```go
// MarshalText implements encoding.TextMarshaler.
func (uk UnlockKey) MarshalText() ([]byte, error) {
return marshalHex(uk.Algorithm.String(), uk.Key[:])
}
```
Causes UnlockKey to JSON encode as `"\"ed25519\":48a468d62e48e27ef24707bd1f467476e9605954e201834c659e614b9704d041"`
This will likely break a bunch of things in `hostd` and `renterd`. Is adding compatibility code for this in `core` worth it?
> Remove quotes from Specifier.String()

- rhp/v2/rhp.go
To avoid accidentally dialing localhost in case the port is set but the address isn't.
> Have SiamuxAddr return an empty string if no host was specified in the settings

- rhp/v2/contracts.go
- rhp/v3/contracts.go
`hostKey` is passed to `PrepareContractRenewal`, although it is not used there.
> Remove unused hostKey from renewal params

- chain/db.go
- chain/manager.go
- chain/manager_test.go
- consensus/update_test.go
- consensus/validation_test.go
This began as an effort to make the DB commit less frequently, which is important for speeding up IBD. Currently, we commit (i.e. fsync) after every block, which means hundreds of thousands of fsyncs are required for a full IBD -- often many fsyncs per second. Needless to say, this is enormously wasteful. Ideally, we would fsync once every few seconds, and/or after buffering a large number of writes. So that's what this PR does: it tracks how long it's been since the last fsync, and how many writes we've buffered since then, and only flushes after we cross a threshold.
In the course of implementing this, I realized that our `DB` interface was more powerful than necessary. Specifically, it supports fully-isolated transactions, meaning you can have multiple "views" of the DB open …
> Refactor DB

- chain/db.go
- types/encoding.go
Prevent an unnecessary 1 KB allocation from being repeated in all the `put` calls.
> Reuse encoder in DB

- .github/workflows/nightly.yml
- .github/workflows/test.yml
Fixes the node12 deprecation warning
> Bump version for checkout and setup-go actions

- rhp/v2/merkle.go
- rhp/v2/rhp.go
This PR adds the `rpcCost` type from `hostd`. We can move it over to `core` and get rid of some of the very rough estimates for proof sizes and replace them by exact values we get from `DiffProofSize`.
> RPCCost (RHPv2)

- rhp/v2/rhp.go
I was working around this in both `renterd` and `hostd` but it's easier to update it here instead.
> HostSettings Value Receiver

- consensus/update_test.go
- consensus/validation_test.go
- gateway/encoding.go
- types/encoding.go
Add a test similar to TestP2P in walletd and add some extra cases mostly relating to file contracts to the validation test.
> More tests for its-happening

- consensus/merkle.go
- consensus/state.go
- types/encoding.go
- types/hash.go
- types/types.go
This is a slightly bigger change, so I figured I'd PR it to allow for some discussion instead of just pushing it.
Sia computes a lot of hashes. When I started implementing v2, I took care to make hashing as fast as possible. In particular, I wanted hashing operations to be zero-alloc. That meant accepting some ugliness like `hasherPool` and eschewing helper functions that might not be inlined.
This PR essentially reverses that decision. Instead of every `ID` function grabbing a hasher and directly calling `EncodeTo` on all the stuff we want to encode, we now pass those things to a magic `hashAll` helper function. The resulting code is definitely more readable; you can see at a glance exactly what's being hashed. The downside is that all of our hashes now allocate, making them a bit …
> types,consensus: Add hashAll helper

- consensus/merkle_test.go
- consensus/update.go
- consensus/update_test.go
- consensus/validation_test.go
Get consensus coverage up to 79.8%
> Add a few tests

- rhp/v2/contracts.go
- rhp/v3/contracts.go
We ran into bugs related to determining the right amount of collateral when renewing contracts. Most notably exceeding the max collateral setting of hosts.
There were multiple reasons for that. I was able to get rid of most errors by postponing computing the collateral until after we have acquired a contract.
The other issue, which is the reason for this PR, is the fact that we used `ContractRenewalCollateral` to compute the `newCollateral` and then `CalculateHostPayouts` to create the payouts and both of these functions perform the same math but slightly different. (one uses fc.EndHeight() and the other one fc.WindowEnd` for determining the extension of the renewal).
Since we don't use rhpv2 renewals I'm not going to bother refactoring that but I'm updating rhpv3 to make sure there is no …
> Add `RenewalCosts` to rhpv3 

- consensus/merkle.go
- consensus/state.go
- rhp/v2/encoding.go
- rhp/v2/rhp.go
- rhp/v3/encoding.go
- rhp/v3/rhp.go
- types/encoding.go
- types/hash.go
- types/multiproof.go
The current encoding of `Currency` uses an 8-byte length prefix followed by a variable-length big-endian encoding of the integer. This is inherently wasteful, as currency values never require more than a 1-byte prefix. Variable-length encodings can also hurt performance in certain use cases, and make it harder to predict the real-world size of various encoded payloads.
This PR adds an alternative fixed-width (16-byte) little-endian encoding for `Currency`. This matches the actual struct definition of `Currency` in `core`: two `uint64`s. Surprisingly, this is not quite as efficient as simply reducing the 8-byte prefix to a 1-byte prefix; the currency values currently present in the blockchain would encode to between 11-15 bytes on average. Still, the advantages of fixed width outweigh the …
> Add more compact v2 encodings

- types/currency.go
- types/currency_test.go
```
Old: "~2.529 mS"
New: "2.529378333356156158367 mS"
```
We discussed removing the SI units as well, and using SC exclusively (i.e. the example above would be `2.529378333356156158367 mS`), but there was less consensus on that.
Since `String` is now exact, `ExactString` has been removed; if you want raw Hastings values, you can use `Big` or `fmt.Sprintf("%d", c)`. If you want a rounded value, you can use standard approaches to round the `float64` returned by `Siacoins`.
> types: Make (Currency).String exact

- internal/blake2b/blake2b_amd64.s
- internal/blake2b/gen.go
Before
```
goos: linux
goarch: amd64
pkg: go.sia.tech/core/internal/blake2b
cpu: AMD EPYC 7B13 64-Core Processor                
BenchmarkBLAKE2b/SumLeaves-128           4167430               290.8 ns/op       880.38 MB/s           0 B/op          0 allocs/op
BenchmarkBLAKE2b/SumNodes-128            3793945               285.3 ns/op       897.44 MB/s           0 B/op          0 allocs/op
PASS
ok      go.sia.tech/core/internal/blake2b       4.610s
```
After
```
goos: linux
goarch: amd64
pkg: go.sia.tech/core/internal/blake2b
cpu: AMD EPYC 7B13 64-Core Processor                
BenchmarkBLAKE2b/SumLeaves-128           6697410               176.7 ns/op      1448.80 MB/s           0 B/op          0 allocs/op
BenchmarkBLAKE2b/SumNodes-128            5853004               181.6 ns/op …
```
> Increase sector root performance

- types/policy_test.go
I started writing this code during the last hackathon for fun, practicing writing test cases. But I didn't finish it because I had to switch to the main task regarding consensus coverage. I felt bad for wipe out a work that had been done, so I ended up finishing the code and also making some changes to it. Initially, I was only aiming to cover the `SatisfiedPolicy` but got carried away and started covering the `PolicyTypeAbove` and `PolicyTypePublicKey`, completely overlooking the fact that you had already done this 😅 Anyway, here it is. I hope that this alternative approach and the additional scenarios will prove valuable to you 🙏
> Add Test Coverage for SatisfiedPolicy and enhance SpendPolicy tests

- consensus/merkle_test.go
This PR expands test coverage in merkle to 95.1% and overall consensus coverage to 76.2%
Now that we have the coverage for DecodeFrom and EncodeTo I'm planning to add a roundtrip later, assuming you find such tests to be valuable.
> Add test coverage for ElementAccumulator.DecodeFrom

- types/currency_test.go
- types/types.go
> types: Prevent unmarshalHex panic on too-long input

- gateway/encoding.go
(note: confirmed this fixes memory leak on my node)
> Avoid reallocating memory for blocks in RPCSendBlocks

- rhp/v3/encoding.go
Something crashed Arequipa by returning a huge `OutputLength`. 10MiB should be plenty.
> Add maxOutputLength to limit slice creation in RPCExecuteProgramResponse

- internal/smux/session.go
- internal/smux/stream.go
I'm not entirely sure that we need to do it per se in these three instances but in the context of the memory leaks we're seeing I think it's good practice to drain the timer channel when stopping them.
> Drain channel when stopping timers

- types/encoding.go
- types/encoding_test.go
Fuzz decoding of SpendPolicy which is probably has the most complicated decoding logic of all the types.  I have been running for ~30 minutes and coverage has not flatlined yet.
Run with:
```
$ go test -fuzz FuzzSpendPolicy ./types
```
> Add SpendPolicy fuzzer

- consensus/validation.go
- consensus/validation_test.go
- types/types.go
@n8maninger noticed a flipped conditional in `validateV2FileContracts`; after fixing it, I updated `TestValidateV2Block` to update the ChainIndexElement proofs, but the test still failed -- with `commitment hash mismatch`, which is a weird error. Further investigation revealed that `V2Block.EncodeTo` was mutating the block. Specifically, it was `nil`-ing out the `V2StorageProof` history proof, which is why this wasn't caught earlier: since the test wasn't updating the proofs in the first place, they were always `nil`, so `EncodeTo` didn't affect them. Anyway, this cascade of failures has all been fixed now :P
> types: Fix (*V2Transaction).DeepCopy mutating V2StorageProof

- types/policy.go
- types/policy_test.go
This changes the policy to stringify and parse the unlock key in the v1 format `specifier:hex key`. You can currently create a valid `PolicyTypeUnlockCondition` using an `UnlockKey` without an ed25519 algorithm, but can't reverse it. This doesn't cause any issues since the v2 validation checks will reject it, but it's slightly annoying that a valid serialization can't be reversed. 
also: I could be wrong, but I believe v1 treated unlock conditions with unknown key algorithms as, effectively, anyone-can-spend. I'm not sure if it was ever actually seen on-chain, but after the require height any unlock condition that used a different algorithm will no longer be spendable.
Current:
```go
sp := SpendPolicy{PolicyTypeUnlockConditions(UnlockConditions{
Timelock: 0,
PublicKeys: []UnlockKey{
{ …
```
> Change unlock conditions policy encoding to be unambiguous

- consensus/merkle.go
- consensus/merkle_test.go
- consensus/state.go
- consensus/update.go
- consensus/update_test.go
- consensus/validation.go
- consensus/validation_test.go
- types/multiproof.go
- types/multiproof_test.go
- types/types.go
This adds a `created bool` argument to the `(Update).ForEach` methods, allowing callers to identify ephemeral elements by checking for `created && spent` (or, in the case of file contracts, `created && resolved`.
This is very useful for any callers who care about persistently tracking unspent outputs. Normally, the code for doing so looks like this:
```go
cau.ForEachSiacoinElement(func(sce types.SiacoinElement, spent bool) {
if spent {
deleteUTXO(sce.ID)
} else {
insertUTXO(sce)
}
})
```
but this is subtly buggy: if the element was ephemeral, `spent` will be true, so we'll try to delete it; but since it's ephemeral, it's not in the set, so there's nothing to delete! Whether or not this causes problems depends on how `deleteUTXO` is implemented. Specifically, if you assert that an element …
> consensus: Expose ephemerality of elements in Apply/RevertUpdate

- types/policy.go
- types/policy_test.go
The old implementation was broken, as evidenced by the test cases I added. Specifically, we were implementing this policy in terms of `PolicyThreshold`, but `PolicyThreshold` requires you to mask any unused public keys with `PolicyOpaque`, which `PolicyTypeUnlockConditions` can't do. We also now handle algorithms other than `SpecifierEd25519` correctly. Overall, this brings validation into agreement with `consensus.validateSignatures`. We can't match its behavior exactly (because v1 transactions contain a list signatures that target specific inputs, while v2 transaction inputs carry their signatures with them), but that's fine; we just need to ensure that any `UnlockConditions` that were satisfiable in v1 are also satisfiable in v2.
> types: Fix PolicyTypeUnlockConditions validation

- consensus/merkle.go
- consensus/validation.go
- consensus/validation_test.go
Previously, `ValidateBlock` (and by extension, `ApplyBlock`) assumed that the supplied `V1BlockSupplement` was valid. This is not entirely unreasonable, since the supplement is computed locally -- unlike the `Block` itself, it is not directly manipulable by an attacker. However, even if a local computation isn't malicious, it can still be buggy! And indeed, we recently discovered that the `consensusDB` helper in `validation_test.go` was not updating the Merkle proofs of its elements, which ultimately lead to a panic in `ApplyBlock`.
This PR adds a `validateSupplement` step to `ApplyBlock`, which ensures that all of the state elements in the supplement exist in the accumulator (and have not been spent or resolved). Note that this is different from how we handle accumulator checks in v2 …
> consensus: Add validateSupplement

- gateway/encoding.go
- rhp/v2/encoding.go
- rhp/v2/rhp.go
- rhp/v2/transport.go
- types/encoding.go
- types/types.go
Specifiers were always intended to be human-readable IDs. This codifies that by escaping non-alphanumeric specifiers during marshaling. Alphanumeric specifiers are marshaled exactly the same as before.
Non-alphanumeric specifiers are fairly rare. The most common offending character is `" "`, which shows up in v1 specifiers like `"siacoin output"`. Also, an early version of the RHP used raw integers in some of its RPC IDs (e.g. `"RPCDownload\x02"`), but those RPCs have been obsolete for many years at this point.
Specifiers are primarily seen in two places: `UnlockKey` algorithms in transaction inputs, and RPC IDs in logs. The latter are developer chosen, so nothing will change there. As for the former, users can technically set the algorithm to whatever they want, but doing so exposes …
> types: Escape non-alphanumeric Specifiers

- consensus/merkle.go
- consensus/update.go
- consensus/update_test.go
This enables consensus "subscription" over HTTP, which in turn allows nodes running on the same machine to share a consensus.db. See https://github.com/SiaFoundation/core/pull/180
This is an unfortunate amount of code. It could be shrunk a little by factoring out the `MidState` marshaling but... meh. It's not the end of the world.
> consensus: Add JSON methods for Updates

- types/policy.go
- types/policy_test.go
The expression-based SpendPolicy encoding is more compact and easier to read, but using it as the standard JSON encoding means that all clients have to write a custom rule, which is annoying. Since most users won't be looking at raw JSON anyway, we might as well make life a bit easier for our devs by switch to a more conventional structural encoding. 
(Note, however, that we still intend to use the expression-based encoding when displaying policies in UIs.)
Thanks to @Alrighttt for surfacing this.
Old:
```
thresh(2, [
above(100),
pk(0x111d2995afa8bf162180a647b9f1eb6a275fe8818e836b69b351871d5caf9c590ed25aec0616),
thresh(2, [
above(200),
pk(0x111d2995afa8bf162180a647b9f1eb6a275fe8818e836b69b351871d5caf9c590ed25aec0616),
]),
]),
```
New:
```
{
"type": "thresh",
"policy": {
"n": 2,
"of": [
{ …
```
> types: Replace expression-based SpendPolicy JSON marshalling

- types/types.go
This field does not follow the consistent use of camelCase for JSON serialization.
> V2FileContractResolution serialization consistency 

- consensus/update.go
- types/types.go
All v1 contracts are considered `valid` in the JSON representation regardless of their resolution. Adds an additional `missed` slice.
> Add missed proofs to update structs

- consensus/merkle.go
- consensus/state.go
- consensus/update.go
- consensus/update_test.go
When iterating over the elements in a `MidState`, we need to be careful with regard to contract revisions. When *applying* a block, we want to report the latest revision; but when *reverting*, we want to report the *earliest*. Unfortunately, this asymmetry was overlooked, leading to a rather pernicious bug: when a block containing a revision is reverted, the Merkle tree is still contains the revision, not the original contract.
It's pernicious because A) reorgs are fairly uncommon, and B) the reorg has to contain a revision, and also C) redundancy in the DB code means that the invalid hashes may be overwritten by valid ones, masking the problem. That's likely why we only discovered this bug after adding a sanity check that validates every block supplement. Sure, our consensus tests *are* …
> consensus: Add (*MidState).forEachRevertedElementLeaf

- consensus/validation.go
- consensus/validation_test.go
Slightly worrisome that I missed this check when porting `siad`... 👀
This demonstrates why it's insufficient to rely on the fact that `core` can sync the existing chain: those are all *valid* blocks. Syncing mainnet tells us nothing about whether `core` will behave the same as `siad` with respect to *invalid* blocks. So we should probably use the fuzzer to pass blocks to both `core` and `siad`, checking that either they both accept or both reject.
> consensus: Disallow contract revision after proof window opens

- consensus/merkle.go
- consensus/update.go
Attestations were being treated as "updated" instead of "created," causing various accumulator-related panics.
Fixes https://github.com/SiaFoundation/coreutils/pull/86
> consensus: Mark attestation elements as created

- consensus/update_test.go
- consensus/validation_test.go
Add v1 apply/revert coverage for siacoin outputs, siafund outputs, file contracts, file contract revisions, and storage proofs as described in https://github.com/SiaFoundation/core/issues/191 and https://github.com/SiaFoundation/core/pull/187#issuecomment-2274189642
> Add v1 apply/revert coverage

- consensus/update_test.go
- consensus/validation_test.go
Add v2 apply/revert coverage for siacoin outputs, siafund outputs, file contracts, file contract revisions, and storage proofs as described in https://github.com/SiaFoundation/core/issues/191 and https://github.com/SiaFoundation/core/pull/187#issuecomment-2274189642
> Add v2 apply/revert coverage

- consensus/state.go
- consensus/validation.go
- consensus/validation_test.go
Fixes a validation regression in the `core` consensus allowing revisions with lower revision numbers in the same block.
> Fix consensus revisions

- consensus/update.go
- consensus/update_test.go
- consensus/validation.go
- consensus/validation_test.go
- types/encoding.go
- types/types.go
Previously, a `V2FileContractFinalization` was a final revision of a contract, mutually agreed upon by the renter and host. However, there are scenarios in which a renter may want to unilaterally end a contract, such as when they want to leave the network entirely. This PR changes `V2FileContractFinalization` to be a signature: specifically, the renter's signature of the current revision, with its revision number set to `MaxRevisionNumber`. This addresses multiple concerns:
- Clearly the renter must not be allowed to finalize a contract revision that lacks a valid host signature. The approach in this PR forces the renter to finalize the *existing* state of the contract, so the host is not at risk.
- The host must not be allowed to finalize contracts at all, since they would be …
> types,consensus: Make contract finalization unilateral

- consensus/update_test.go
- consensus/validation.go
- consensus/validation_test.go
- rhp/v4/encoding.go
- rhp/v4/merkle.go
- rhp/v4/rhp.go
- rhp/v4/validation.go
- types/encoding.go
- types/types.go
> RHP4 spec changes

- consensus/state.go
- consensus/update.go
- consensus/update_test.go
- consensus/validation.go
- consensus/validation_test.go
- types/encoding.go
- types/multiproof_test.go
- types/types.go
This is an experimental change that gives each element type an ID specific to that type, rather than all elements using `types.Hash256` as their ID type. That is, `sce.ID` is now a `types.SiacoinOutputID`. This prevents awkward casts in a few places, namely when deriving output IDs like `types.SiafundOutputID(sfi.Parent.ID).V2ClaimOutputID())` -- we can now write `sfi.Parent.ID.V2ClaimOutputID()` instead.
The second commit un-embeds the `StateElement` field from each element type. Embedding is best avoided unless there are significant benefits, and in this case the only significant benefit was convenient access to the `ID` field, which is now moot.
The combined effect on JSON encodings is:
```json
old:
{
"id": "h:9373b2995a6f5d47d63aaf22dbbfe92aa43b84551fe5de1e08341fd02dd100ec", …
```
> types: Move ID output of StateElement

- types/types.go
- types/types_test.go
This adds the calculated ID for the transaction to the JSON marshaling of a transaction. This is primarily a convenience for API consumers that may or may not have the ability to calculate it easily. I believe `siad` added a calculate endpoint, but it's even more annoying to have to call 2 routes imo.
I decided not to override unmarshal and discard the ID for similar convenience, but it could be desirable to validate the deserialized transaction data against the provided ID. However, that would complicate broadcasting a transaction.
Most recent context, but this comes up quite a lot with integrators: https://discord.com/channels/809849352516141067/809858207064653894/1306241130408443915.
> Add ID field to Transaction and V2Transaction JSON encoding

- types/encoding.go
- types/multiproof_test.go
Previously, we used the policy itself to figure out how many signatures and preimages to expect. This saved two length prefixes (16 bytes), but it was annoying to implement, and also led to a vulnerability: `EncodeTo` panicked when called with the wrong number of signatures or preimages, but `UnmarshalJSON` did not validate these, so you could trigger a panic by causing a node to decode an invalid `SpendPolicy` as JSON and then encode it as binary.
The modal satisfied policy is 1 pubkey + 1 signature, so ~100 bytes, making this a ~16% size increase. Not insignificant, but tolerable.
Note that we don't need any additional validation: `(SpendPolicy).Verify` already checks for superfluous signatures and preimages.
> types: Simplify SatisfiedPolicy encoding

- consensus/state.go
- gateway/encoding.go
- gateway/outline.go
- types/encoding.go
- types/encoding_test.go
- types/types.go
This unifies v1 and v2 block headers and promotes `BlockHeader` from `gateway` to `types`. It also changes how V2 block IDs are computed.
I had previously omitted the `ParentID` from the v2 block "header," because it is incorporated into the `Commitment` field (via the hash of the parent `consensus.State`). This left the first 32 bytes of the 80-byte hash preimage unused, so I filled them with a distinguisher string.
However, after reflecting on how headers are actually used in the Syncer, I think it's better to include the `ParentID` after all, even if it's slightly redundant and not *strictly* necessary. Here's my reasoning, in the form of a dialogue:
- 🤔 Foo: Imagine a peer sends you a v2 header, claiming that they have found the next block. You hash the header and verify that, indeed, …
> Refactor BlockHeader

- consensus/state.go
- consensus/update.go
- consensus/update_test.go
- consensus/validation.go
v2 transactions have a `NewFoundationAddress` field, which, if present, updates both the primary and failsafe addresses. This PR tweaks the update logic slightly: if the new address is `types.VoidAddress`, only the primary address is updated. `(State).FoundationSubsidy` also now returns `false` if the primary address is `types.VoidAddress`. Together, these changes allow the Foundation to effectively waive the subsidy until a new, non-void primary address is set. This is preferable to receiving and then later burning the subsidy; instead, the subsidy is simply not created in the first place.
I also renamed "primary" and "failsafe" to "subsidy" and "management" to reflect the function of these addresses in v2. The "subsidy" address receives the subsidies, while the "management" address is …
> Allow Foundation subsidy to be waived

- consensus/state.go
- consensus/update.go
- consensus/validation.go
- consensus/validation_test.go
- rhp/v4/rhp.go
- types/encoding.go
- types/types.go
The tradeoff is that resolution transactions can't contain other outputs. That doesn't seem too restrictive to me, but maybe I'm forgetting a use case that requires it?
I also noticed that a renewal's `FinalRevision` wasn't being applied to the accumulator that way; instead, the accumulator would contain the most recent revision of the contract. Not a huge deal, just felt inconsistent.
> Simplify V2FileContractRenewal

- consensus/state.go
- consensus/update.go
- consensus/update_test.go
- types/types.go
"Pool" was always a bit of a misnomer, because making a siafund claim doesn't subtract value from the "pool." Its actual function is to record the total revenue at specific points in time, so that we can calculate the delta between two points and thereby determine the value of the dividend.
I also slightly tweaked how dividends are calculated in v2. Previously, all file contract taxes were rounded down to a multiple of 10,000 H, so that they would be evenly divisible by the number of siafunds. But this isn't actually necessary; you can just divide when you calculate the claim value, and the rounding will occur then. This is slightly more fair anyway: as an extreme example, if all contract taxes had a value of 9999 H, siafund holders would never receive any dividends, no matter how many …
> consensus: Rename SiafundPool -> SiafundTaxRevenue

- consensus/validation.go
- consensus/validation_test.go
- rhp/v4/encoding.go
- rhp/v4/rhp.go
Did not notice this until after trying to update coreutils with #238.  The new renewal validation logic was checking the individual payout values against the parent file contract element. This does not account for the payouts changing in an unbroadcast revision. This changes the logic to check that the sum of the outputs is equal to the sum of the parent outputs. Also adds some additional validation tests.
> Fix renewal payout validation

- .changeset/automate_releases.md
- .github/workflows/prepare-release.yml
- .github/workflows/release.yml
- knope.toml
This makes PRs slightly more annoying because they will need to have either a documented change set or conventional commits, but this will automate the release process and improve documentation. This is mostly the same setup as renterd and hostd with the addition of tagging the release when the preview PR closes.
(sorry)
> Automate releases

- rhp/v4/rhp.go
- rhp/v4/rhp_test.go
Slightly different implementation of #251 that does not change the function signature
> fix(rhp4): Include storage cost in renter renewal cost

- consensus/application.go
- consensus/state.go
- consensus/validation.go
- consensus/validation_test.go
After careful testing, I found that `siad` does allow a contract to be resolved within the same block it was created. In short:
- Contracts must have a `WindowStart` of at least `currentHeight+1`
- Storage proofs check that `currentHeight` is not greater than the "trigger height," which is `WindowStart - 1`
- Therefore, if you create a contract with `WindowStart = currentHeight + 1`, its trigger height will be `currentHeight`, so a storage proof is allowed.
So in fact, you can create, revise, and resolve a v1 contract all in the same block! (On that note, the update docstrings are more descriptive now.)
Note that v2 contracts do NOT share this property. There is no such thing as an ephemeral v2 contract; that is, you can't use `types.UnassignedLeafIndex` when referencing a v2 contract. …
> fix(consensus): Allow v1 contracts to be resolved immediately

- .changeset/fix_account_json_encoding.md
- rhp/v4/rhp.go
Fixes the implementation of `encoding.TextMarshaler` on the rhp4.Account type. Will change the JSON encoding of an account from an array to a string.
Fixes an issue raised in https://github.com/SiaFoundation/web/pull/895
> Fix account json

- .changeset/fixed_a_panic_when_unmarshalling_unknown_spend_policy_types.md
- types/policy.go
- types/types_test.go
Fixes a panic in `AddV2PoolTransactions` when validating v2 transactions with nil spend policies. Uses the same strategy as currency overflows to validate once and assumes it is valid afterward. `AddV2PoolTransactions` should be able to handle unvalidated input without panicking.
```
NFO    http: panic serving [::1]:60723: unhandled policy type <nil>
goroutine 713398 [running]:
net/http.(*conn).serve.func1()
/opt/homebrew/opt/go/libexec/src/net/http/server.go:1947 +0xb0
panic({0x103d2e900?, 0x140004bfd00?})
/opt/homebrew/opt/go/libexec/src/runtime/panic.go:785 +0x124
go.sia.tech/core/types.SpendPolicy.encodePolicy({{0x0?, 0x0?}}, 0x1?)
/Users/alexfreska/go/pkg/mod/go.sia.tech/core@v0.9.1/types/encoding.go:604 +0x3a0
go.sia.tech/core/types.SpendPolicy.EncodeTo({{0x0?, 0x0?}}, …
```
> Fix panic when validating v2 transactions

- .changeset/consensus_diffs.md
- consensus/application.go
- consensus/application_test.go
- consensus/merkle.go
- consensus/state.go
- consensus/validation.go
- consensus/validation_test.go
- types/multiproof_test.go
This replaces the `ForEach` update API with slices of "diffs" -- new types wrapping the various element types. This was originally intended as an ergonomics improvement (since it's annoying to e.g. break out of a `ForEach` callback), but it ended up significantly simplifying most `MidState`-related code: it consolidated the interrelated maps within `MidState`, and enabled a much saner rewrite of the update JSON types.
I originally left the `ForEach` methods in place (with a `// Deprecated` warning), but later removed them entirely; we're going to update all the callsites in `coreutils` anyway, so there's little reason to keep them around. (`ForEachTreeNode` remains, though, since it's used by `explored`.)
> Consensus diffs

- .changeset/add_helpers_to_get_revision_as_an_element_from_v1v2_file_contract_element_diffs.md
- consensus/state.go
See https://github.com/SiaFoundation/explored/pull/169#discussion_r1950507575
> Add helpers to get revision as an element from v1/v2 file contract element diffs

- .changeset/add_rpcreplenish_to_rhp4.md
- rhp/v2/contracts.go
- rhp/v3/contracts.go
- rhp/v4/encoding.go
- rhp/v4/rhp.go
- rhp/v4/validation.go
Adds an RPC to RHP4 that enables renters to set a target balance for all accounts instead of first fetching the current balances then funding the accounts with the difference. This is primarily to speed up account funding and reduce round trips when managing a large number of accounts.
> Add RHP4 RPC replenish types

- rhp/v4/encoding.go
`reasonableObjectSize` is not enough for these batch types
> rhp4: Use MaxAccountBatchSize for encoding sizes

- .changeset/increase_speed_of_sector_root_calculation_by_10x.md
- rhp/v2/merkle.go
- rhp/v2/merkle_test.go
- rhp/v4/merkle_test.go
```
goos: darwin
goarch: arm64
pkg: go.sia.tech/core/rhp/v2
cpu: Apple M2 Pro
BenchmarkSectorRoot
BenchmarkSectorRoot/serial
BenchmarkSectorRoot/serial-10                 49          23381873 ns/op         179.38 MB/s           0 B/op          0 allocs/op
BenchmarkSectorRoot/parallel
BenchmarkSectorRoot/parallel-10              326           3563796 ns/op        1176.92 MB/s       14806 B/op         34 allocs/op
```
Pretty unambiguous  ~10x speedup when testing with a 10-core CPU. I experimented with inlining more of the `appendLeaves` logic into the worker goroutines, but it didn't have a significant impact on throughput and it made the code much more complex. ‾\\\_(ツ)\_/‾
> rhp: Parallelize SectorRoot

- rhp/v4/encoding.go
There are several instances where `maxLen` returns a size that doesn't take into account a transaction being part of the request. While updating I noticed some values diverged from their impl probably due to changes being made to the request/response structs over time. I took them along with me but the important ones are the `reasonableTransactionSetSize` ones of course.
I found out because my v2 migration on my node, which was chugging along nicely, halted all of a sudden. Contracts were no longer being refreshed, resulting in empty accounts, resulting in failed migrations. One thing that's puzzling me a bit though is the error message: "couldn't renew/refresh contract: host responded with error: failed to read host inputs response: failed to read request: EOF ". That error message seems …
> Fix `maxLen`

- knope.toml
https://github.com/SiaFoundation/core/pull/284 did not have a changeset entry, but that was done on purpose. I looked through recently merged core PRs and noticed we don't always add it, figured that fix did not really need one per se either. I updated the `knope` config to be consistent with all other repos.
> Update `knope` config

- .changeset/add_mul_helper_to_usage_type.md
- rhp/v4/rhp.go
This adds a useful helper to `Usage`. e.g. when computing how much funds to put into a contract it's nice to be able to do `RPCAppendSectorCost.Mul(sectorsPerTiB)` or whatever.
> Add mul to Usage

- consensus/application.go
- consensus/application_test.go
- consensus/merkle.go
- consensus/state.go
- consensus/validation.go
- consensus/validation_test.go
- go.mod
- go.sum
- internal/lint/cmd/elmo/main.go
- types/multiproof_test.go
- types/types.go
This should go a long way towards catching memory aliasing bugs like https://github.com/SiaFoundation/core/pull/290. I should have done this ages ago. 😬 Basically, the linter flags anything like:
```go
sce := txn.SiacoinInputs[0].Parent // "shallow copy of SiacoinElement; use Move, Share, or Copy"
cau.UpdateElementProof(&sce)
```
To silence it, you annotate each copy with one of those ownership methods, and then we panic if you try to call `UpdateElementProof` on an element that you don't exclusively own.
Annotating every copy is kind of annoying, but it wasn't too onerous to churn through them once the linter was working. In case it's not clear, the idea is:
- Default to `Copy`.
- If you're not going to retain the element (e.g. if you're a function that just inspects elements and returns …
> all: Add Element memory management methods and linter

- .changeset/consider_post_refresh_values_for_the_minrenterallowance_check_rather_than_the_additional_values.md
- rhp/v4/validation.go
I ran into a min allowance issue on Zen which made me reread this part of the code and I noticed that the current behavior for refreshing contracts is not necessarily what we want.
Before this PR, we make sure the ratio of newly added allowance and collateral is sane during a refresh. However, if a contract still has plenty of allowance left in it, this shouldn't affect our ability to refresh this contract without pouring more renter funds into it if the ratio is still sane *after* the refresh. 
So this PR changes the check to consider the ratio of unused collateral+allowance after the refresh rather than the one of the added values.
> Update refresh validation to consider post refresh allowance and collateral

- .changeset/add_maxhostcollateral_helper.md
- .changeset/removed_duration_parameter_from_minrenterallowance_helper.md
- rhp/v4/rhp.go
- rhp/v4/rhp_test.go
- rhp/v4/validation.go
This PR adds `MaxHostCollateral` as a counterpart to `MinRenterAllowance`.
It also removes the `duration` since it doesn't affect the outcome of the functions since the ratio stays the same regardless of the duration.
> Add MaxHostCollateral

- rhp/v4/rhp.go
- rhp/v4/rhp_test.go
- rhp/v4/validation.go
Reverts #298 to the old behavior and removes unused params.
Looking at the original PR, #298, I think the logic change there is actually incorrect. It's not clear to me why a contract refresh would ever have plenty of allowance but not enough collateral since the funds always flow from the renter to the host. 
The subtest that got changed in https://github.com/SiaFoundation/coreutils/pull/215 should have been a valid state based on the intended behavior.
The desired behavior is that the host's total collateral locked is a consistent ratio with the renter's total spending. In the case of that subtest, the renter has locked `110 SC` total and the host has locked `220 SC` total. With the new logic, that is now considered a bad state because the renter spent `25 SC` of its allowance funding …
> Clean up validation

- .changeset/adds_an_address_field_to_the_json_representation_of_siacoin_and_siafund_inputs.md
- types/types.go
Similar to the `id` field on Transactions, adds `address` to the json representation of Siacoin and Siafund inputs for ease of use in other languages.
> Add address field

- consensus/application_test.go
- consensus/state.go
- consensus/state_test.go
- consensus/validation.go
- consensus/validation_test.go
- gateway/gateway_test.go
- gateway/outline.go
- types/hash_test.go
This restores compatibility with the Stratum mining protocol. Stratum servers simply need to include an additional leaf hash when computing the Merkle tree:
```go
hashAll(uint8(0), "commitment", s.v2ReplayPrefix(), types.Hash256(hashAll(s)), minerAddr)
```
Of course, once the RequireHeight is reached and v1 transactions are no longer allowed, they will also need to adjust the `Coinbase1` and `Coinbase2` values they send, to account for the different encoding of v2 transactions.
> consensus: Change Commitment to a Merkle root

- .changeset/added_statemerkleleafhash_helper.md
- consensus/state.go
- gateway/outline.go
Added `MerkleLeafHash` helper similar to `Transaction.MerkleLeafHash` to reduce duplication. Also changed from using `hashAll` because it makes it harder for external devs to notice the distinguisher encoding.
> Added helper for merkle leaf hash

- .changeset/add_rpcsendheaders.md
- consensus/application.go
- consensus/validation.go
- gateway/encoding.go
Also removes `RPCSendBlocks` and `RPCSendBlk` (made obsolete by `RPCSendV2Blocks` and `RPCSendCheckpoint`), as well as `RPCRelayHeader` and `RPCSendTransactionSet` (as no more v1 blocks or v1 transactions can be mined). I could maybe see an argument for keeping the latter two, if we wanted to run a v1 testnet, but... why would we want to run a v1 testnet?
> Add RPCSendHeaders

- .changeset/v2-the-final-cut.md
- consensus/application.go
- consensus/application_test.go
- consensus/state.go
- consensus/validation.go
- consensus/validation_test.go
The difficulty adjustment algorithm in v2 was intended to be a straight port of v1, merely swapping "target" for "difficulty" and cleaning up some historic cruft. Unfortunately, it also introduced a bug, which has led to increased variance in block times. This caused the v2 require height to be reached earlier than expected. Block times have slowly normalized, but until the bug is fixed, there is no guarantee they will remain normal.
After reviewing the v1 algorithm, I have opted to change the squared error term to a proportional error, with the same target of "10,000 seconds of drift = 10 seconds of shift." Squaring the error means that, when approaching zero, the adjustment shrinks faster than the error does, meaning we never quite reach zero error. It also does not correct large errors …
> v2: The Final Cut

- .changeset/expose_helper_methods_to_compute_the_remaining_allowance_collateral_risked_collateral_and_risked_revenue_on_the_v2filecontract_type.md
- rhp/v4/rhp.go
- rhp/v4/rhp_test.go
- types/types.go
Since the revenue related contract fields are not the easiest to wrap you head around I added some documentation on the `V2FileContract` type as well as helpers for some frequently done math. 
I also added `RemainingAllowance` and `RemainingCollateral` which are more or less just aliases but imo they still make contracts nicer to use. The fields `MissedHostValue` and `RenterOutput` are technically correct but make more sense when looked at in the context of the consensus code and the methods `RemainingCollateral` and `RemainingAllowance` feel more intuitive when used in the context of the RHP.
> Document `V2FileContract` type and add useful helpers for revenue calculations
