consensus/scratch_test.go, consensus/update_test.go, consensus/validation_test.go, internal/chainutil/chainutil_test.go, merkle/multiproof_test.go, net/rhp/session.go, types/encoding.go
Separates external packages in all source files
=> Fix package ordering

.github/workflows/nightly.yml
Runs the test suite nightly with -count=1000 to try and detect NDFs
=> ci: add nightly test workflow

net/mux/encryption.go, types/types.go
Adds helper funcs for calculating output and contract IDs from #34
=> Add id helper methods

host/executor.go, host/host.go, net/rhp/contracts.go, net/rhp/merkle.go, net/rhp/merkle_test.go, net/rhp/rpc.go
Add a `ReadSector` method to the `rhp` package, modify the program executor to use it, and update the host interfaces with additional changes.
=> Add ReadSector method

net/rhp/contracts.go
Separates the contract revision helpers from the contract type.
=> Add contract revision helpers

host/host.go, net/rhp/rpc.go, net/rhp/settings.go
Changes the transaction pool interface to match the change made in siafoundation/siad#78
=> Update TransactionPool interface

consensus/validation.go, consensus/validation_test.go
I'm not sure how multiple updates would affect the accumulator today, but it probably isn't pretty. (Meaning, it probably doesn't cause a validation error, but instead produces an invalid `ApplyUpdate` that can screw up your proofs.)
We *could* make an extra effort to allow this behavior; specifically, we would have to ensure that only the last revision/resolution is used for accumulator updates. But why not move that logic to the txpool instead? That is, if the txpool contains 2 transactions that revise the same contract, why not discard the one with the lower revision number? It would just waste block space anyway.
On that note, we should update `(ValidationContext).ValidateTransaction` to catch double-spends (and double-updates) within a single transaction, so that the txpool can …
=> consensus: Disallow contracts from being updated multiple times per block

net/rhp/merkle.go, net/rhp/merkle_test.go
Adds the `us` functions to build storage proofs
=> Add storage proof functions

types/policy.go, types/policy_test.go
Adds support for parsing SpendPolicys encoded with SpendPolicy.String() and accordingly adds a JSON unmarshaler function.  Also adds a new `TestPolicyJSON` that tests an encoding "round trip" (marshaling then unmarshaling) for a bunch of policies.
=> Add SpendPolicy JSON unmarshaling

chain/manager.go, chain/manager_test.go, consensus/scratch_test.go, consensus/state.go, consensus/validation.go, consensus/validation_test.go, internal/chainutil/chainutil.go
Also restore the future block validation check, but in `chain.Manager` rather than consensus.
=> consensus: Make NonceFactor a State method

internal/chainutil/store.go, merkle/multiproof.go, merkle/multiproof_test.go, types/encoding.go
Unlike many blockchains, Sia has never explicitly versioned its blocks or transactions. Instead, we relied on the `ArbitraryData` field: for example, as part of the Foundation subsidy hardfork, we added consensus code that checks for the presence of a `FoundationUnlockHashUpdate` within the `ArbitraryData`.
This has worked fine in practice, but it has limitations. We can't change the block header format, for example. And certain changes, such as modifying an existing transaction field (including `ArbitraryData` itself!) could get pretty ugly. Directly versioning our blocks and transactions solves these problems.
Currently, my plan here is to take the same approach that Go recommends for versioning modules. If we need to break header or transaction compatibility, we will define new types: …
=> Add version byte to Block and Transaction encoding

rhp/v3/transport.go
+ Changes `NewHostTransport` to accept the incoming stream from the renter for the app seed handshake
+ Changes the subscription response to a length-prefixed, length-prefixed string to match `siad`
=> rhp/v3: fix host app seed and subscription handshake

chain/db.go, chain/manager.go, consensus/state.go, consensus/update.go, consensus/validation.go, go.sum, types/currency.go, types/currency_test.go, types/encoding.go, types/types.go
This implements a chain manager that can accept blocks, attach them to the best chain, compute the resulting state and effects, and apply those effects to a database.
=> chain: Add package

chain/db_test.go, consensus/update.go, consensus/validation.go
Add consensus tests like some of the ones we have in v2.  Test cases for file contracts coming shortly.
=> Add Consensus Validation Tests

chain/db_test.go
Add tests that cover most of the contract creation/revision related code in consensus/validation.go and a case for a block that exceeds the maximum weight.
=> Add file contract consensus tests

rhp/v2/rhp.go, rhp/v3/rhp.go, types/types.go
This came up in a [`renterd` review](https://github.com/SiaFoundation/renterd/pull/264#discussion_r1160522122) the other day so I decided to propose it. I'm still not sure whether it's silly or actually useful so I figured I would let you be the judge Luke. Definitely feel free to just close this out, I was expecting way more occurrences to be honest, was surprised to only find a handful.
=> RenterOutputIndex and HostOutputIndex Constants

rhp/v2/rhp.go
=> Add release to rhp2 settings

types/policy_test.go
This PR expands test coverage in `policy.go` to 86.5% and overall `types` coverage to 59.7%
=> Add test coverage for SatisfiedPolicy.MarshalJSON

consensus/state.go, consensus/update.go, consensus/update_test.go, consensus/validation.go
Fixes #203 
I'll follow this up with a regression test in `coreutils`.
=> consensus: Add V1StorageProofSupplement, fixing encoding bug

consensus/validation_test.go, types/encoding.go, types/encoding_test.go, types/policy.go, types/policy_test.go, types/types.go
=> types: Switch to fixed-length PolicyHash preimage

consensus/validation.go, consensus/validation_test.go, rhp/v4/validation.go
Removes the need for a setup transaction for v2 contract resolutions
=> Remove resolution txn restrictions

rhp/v4/encoding.go, rhp/v4/rhp.go, rhp/v4/validation.go
Add explicit refresh RPC for more efficient and correct contract refreshes
=> RPC refresh

consensus/update_test.go, types/encoding.go, types/types.go
`consensus.hashAll` panics when a transaction has an Attestation
=> Implement interfaces for AttestationID

.gitignore, rhp/v4/rhp.go, rhp/v4/validation.go
=> Fix collateral validation for RPC renew and refresh

.changeset/fix_siafund_claimstart.md, consensus/application.go, consensus/application_test.go
=> consensus: Fix Siafund ClaimStart not being recorded

rhp/v4/rhp.go
Adds some doc comments to the RHP4 settings
=> chore(doc): comment rhp4 settings

gateway/encoding.go
=> gateway: Fix missing SendCheckpoint RPC
